'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fib(number):
    if number == 1 or number == 2:
        return 1
    else:
        return fib(number-1) + fib(number-2)

i = 1 
result = 0   
while fib(i) < 4000000:
    if fib(i) % 2 == 0:
        result += fib(i)
    i += 1

print result

